service: gohomenotes
provider: aws
functions:

resources:
  Resources:
    usersTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ghusers
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1